Installing pandas

In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\vdes3012\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\vdes3012\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\vdes3012\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------------------- -------------------- 4.7/9.9 MB 34.2 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 28.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 28.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 11.8 MB/s  0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.2 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## **Stage 1**
- Data Ingestion

In [2]:
import pandas as pd

In [3]:
deliveries_df = pd.read_csv("deliveries.csv")
matches_df = pd.read_csv("matches.csv")

In [4]:
deliveries_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [5]:
matches_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [6]:
deliveries_df.shape

(260920, 17)

In [7]:
matches_df.shape

(1095, 20)

In [8]:
for col in deliveries_df:
    print(type(col))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [9]:
for col in matches_df:
    print(type(col))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [10]:
deliveries_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [11]:
matches_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

## **Stage 2**
- Data Cleaning & Validation

In [12]:
print(deliveries_df.isnull().sum())

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [13]:
print("Duplicate rows:", deliveries_df.duplicated().sum())

Duplicate rows: 0

In [14]:
print(deliveries_df['batting_team'].unique())
print(deliveries_df['dismissal_kind'].unique())

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',             'Kings XI Punjab',
            'Rajasthan Royals',            'Delhi Daredevils',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str
<StringArray>
[                    nan,                'caught',                'bowled',
               'run out',                   'lbw',          'retired hurt',
               'stumped',     'caught and bowled',            'hit wicket',
 'obstructing the field',           'retired out']
Length: 11, dtype: str

In [15]:
deliveries_df['dismissal_kind'] = deliveries_df['dismissal_kind'].replace({
    'run out ': 'run out',
    'NA': None
})

In [16]:
print(deliveries_df[deliveries_df['total_runs'] < 0])

Empty DataFrame
Columns: [match_id, inning, batting_team, bowling_team, over, ball, batter, bowler, non_striker, batsman_runs, extra_runs, total_runs, extras_type, is_wicket, player_dismissed, dismissal_kind, fielder]
Index: []

In [17]:
print(deliveries_df.dtypes)

match_id            int64
inning              int64
batting_team          str
bowling_team          str
over                int64
ball                int64
batter                str
bowler                str
non_striker           str
batsman_runs        int64
extra_runs          int64
total_runs          int64
extras_type           str
is_wicket           int64
player_dismissed      str
dismissal_kind        str
fielder               str
dtype: object

In [18]:
deliveries_df['extras_type'] = deliveries_df['extras_type'].fillna('No Extra')

deliveries_df['player_dismissed'] = deliveries_df['player_dismissed'].fillna('Not Out')

deliveries_df['dismissal_kind'] = deliveries_df['dismissal_kind'].fillna('Not Dismissed')

deliveries_df['fielder'] = deliveries_df['fielder'].fillna('No Fielder Involved')

In [19]:
print(deliveries_df.isnull().sum())

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

## **Stage 3**
- Data Transformation

In [20]:
deliveries_df["ball_id"] = (
    deliveries_df["match_id"].astype(str) + "_" +
    deliveries_df["inning"].astype(str) + "_" +
    deliveries_df["over"].astype(str) + "_" +
    deliveries_df["ball"].astype(str)
)

In [21]:
deliveries_df["is_boundary"] = deliveries_df["batsman_runs"].apply(
    lambda x: 1 if x in [4, 6] else 0
)

In [22]:
deliveries_df["is_four"] = (deliveries_df["batsman_runs"] == 4).astype(int)

deliveries_df["is_six"] = (deliveries_df["batsman_runs"] == 6).astype(int)

In [23]:
deliveries_df["is_dot_ball"] = (deliveries_df["total_runs"] == 0).astype(int)

In [24]:
matches_df["date"] = pd.to_datetime(matches_df["date"])

In [25]:
deliveries_df.columns = deliveries_df.columns.str.lower().str.strip().str.replace(" ","_")
matches_df.columns = matches_df.columns.str.lower().str.strip().str.replace(" ","_")

## ***Stage 4***
- Core Analysis

#### Total Runs per Match

In [26]:
total_runs_match = deliveries_df.groupby("match_id")["total_runs"].sum()
print(total_runs_match.head())

match_id
335982    304
335983    447
335984    261
335985    331
335986    222
Name: total_runs, dtype: int64

Runs Per Team Per Match

In [27]:
team_match_runs = deliveries_df.groupby(
    ["match_id", "batting_team"]
)["total_runs"].sum().reset_index()

print(team_match_runs.head())

   match_id                 batting_team  total_runs
0    335982        Kolkata Knight Riders         222
1    335982  Royal Challengers Bangalore          82
2    335983          Chennai Super Kings         240
3    335983              Kings XI Punjab         207
4    335984             Delhi Daredevils         132

Top 10 Batters

In [28]:
top_batters = deliveries_df.groupby("batter")["batsman_runs"]\
.sum().sort_values(ascending=False).head(10)

print(top_batters)

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
MS Dhoni          5243
AB de Villiers    5181
CH Gayle          4997
RV Uthappa        4954
KD Karthik        4843
Name: batsman_runs, dtype: int64

Strike Rate of Batters

In [29]:
strike_rate = deliveries_df.groupby("batter").agg({
    "batsman_runs":"sum",
    "ball":"count"
})

strike_rate["strike_rate"] = (
    strike_rate["batsman_runs"] / strike_rate["ball"]
) * 100

print(strike_rate.sort_values("strike_rate", ascending=False).head(10))

                 batsman_runs  ball  strike_rate
batter
L Wood                      9     3   300.000000
B Stanlake                  5     2   250.000000
J Fraser-McGurk           330   150   220.000000
R Sai Kishore              13     6   216.666667
Umar Gul                   39    19   205.263158
RS Sodhi                    4     2   200.000000
Shahid Afridi              81    46   176.086957
I Malhotra                  7     4   175.000000
WG Jacks                  230   133   172.932331
PD Salt                   653   385   169.610390

Top 10 Bowlers by Economy

In [30]:
bowler_stats = deliveries_df.groupby("bowler").agg({
    "total_runs":"sum",
    "ball":"count"
})

bowler_stats["overs"] = bowler_stats["ball"] / 6
bowler_stats["economy"] = (
    bowler_stats["total_runs"] / bowler_stats["overs"]
)

print(bowler_stats.sort_values("economy").head(10))

               total_runs  ball     overs   economy
bowler
AC Gilchrist            0     1  0.166667  0.000000
R Ravindra              7    12  2.000000  3.500000
NB Singh               18    25  4.166667  4.320000
Sachin Baby             8    10  1.666667  4.800000
AM Rahane               5     6  1.000000  5.000000
LA Carseldine           6     7  1.166667  5.142857
SS Mundhe               6     7  1.166667  5.142857
DJ Thornely            40    44  7.333333  5.454545
M Manhas               42    42  7.000000  6.000000
MW Short               25    25  4.166667  6.000000

Most Consistent Batters

In [31]:
batter_match_runs = deliveries_df.groupby(
    ["batter","match_id"]
)["batsman_runs"].sum().reset_index()

consistency = batter_match_runs.groupby("batter").agg({
    "batsman_runs":"mean",
    "match_id":"nunique"
})

consistent_batters = consistency[
    consistency["match_id"] >= 20
].sort_values("batsman_runs", ascending=False)

print(consistent_batters.head(10))

                 batsman_runs  match_id
batter
DP Conway           42.000000        22
B Sai Sudharsan     41.360000        25
KL Rahul            38.434426       122
LMP Simmons         37.206897        29
RD Gaikwad          36.615385        65
SE Marsh            36.072464        69
DA Warner           35.690217       184
CH Gayle            35.439716       141
ML Hayden           34.593750        32
MEK Hussey          34.086207        58

Highest Individual Score in a Match

In [32]:
highest_score = deliveries_df.groupby(
    ["match_id","batter"]
)["batsman_runs"].sum().reset_index()

print(highest_score.sort_values(
    "batsman_runs",
    ascending=False
).head(1))

      match_id    batter  batsman_runs
5302    598027  CH Gayle           175

Boundary Analysis

In [33]:
total_fours = (deliveries_df["batsman_runs"] == 4).sum()
total_sixes = (deliveries_df["batsman_runs"] == 6).sum()

print("Total Fours:", total_fours)
print("Total Sixes:", total_sixes)

Total Fours: 29850
Total Sixes: 13051

Boundary Percentage

In [34]:
boundary_runs = deliveries_df[
    deliveries_df["batsman_runs"].isin([4,6])
].groupby("batter")["batsman_runs"].sum()

total_runs = deliveries_df.groupby("batter")["batsman_runs"].sum()

boundary_percentage = (
    boundary_runs / total_runs
) * 100

print(boundary_percentage.sort_values(
    ascending=False
).head(10))

batter
P Chopra           100.000000
GD McGrath         100.000000
VRV Singh          100.000000
A Tomar            100.000000
RS Sodhi           100.000000
BA Bhatt           100.000000
Liton Das          100.000000
R Sai Kishore       92.307692
J Fraser-McGurk     89.696970
AA Kulkarni         88.888889
Name: batsman_runs, dtype: float64

Dot Ball Analysis

In [35]:
dot_balls = deliveries_df[
    deliveries_df["total_runs"] == 0
]

top_dot_bowlers = dot_balls.groupby(
    "bowler"
).size().sort_values(
    ascending=False
).head(10)

print(top_dot_bowlers)

bowler
B Kumar            1632
SP Narine          1569
R Ashwin           1552
PP Chawla          1325
Harbhajan Singh    1263
JJ Bumrah          1228
RA Jadeja          1216
YS Chahal          1194
UT Yadav           1186
A Mishra           1185
dtype: int64

Runs Per Over Analysis

In [36]:
runs_per_over = deliveries_df.groupby(
    "over"
)["total_runs"].mean()

print(runs_per_over)

over
0     0.981663
1     1.173528
2     1.316099
3     1.356538
4     1.369100
5     1.373055
6     1.103107
7     1.189948
8     1.242087
9     1.224577
10    1.262623
11    1.287686
12    1.301240
13    1.343645
14    1.393504
15    1.434273
16    1.498778
17    1.587839
18    1.646896
19    1.776855
Name: total_runs, dtype: float64

Powerplay Analysis (1–6)

In [37]:
powerplay = deliveries_df[
    deliveries_df["over"] <= 6
]

powerplay_runs = powerplay.groupby(
    "batting_team"
)["total_runs"].sum().sort_values(
    ascending=False
)

print(powerplay_runs.head(10))

batting_team
Mumbai Indians                 13943
Kolkata Knight Riders          13632
Chennai Super Kings            12631
Royal Challengers Bangalore    12429
Rajasthan Royals               11774
Kings XI Punjab                10295
Sunrisers Hyderabad            10170
Delhi Daredevils                8503
Delhi Capitals                  5358
Deccan Chargers                 3889
Name: total_runs, dtype: int64

Death Over Analysis (16–20)

In [38]:
death_overs = deliveries_df[
    deliveries_df["over"] >= 16
]

death_runs = death_overs.groupby(
    "batting_team"
)["total_runs"].sum().sort_values(
    ascending=False
)

death_batters = death_overs.groupby(
    "batter"
)["batsman_runs"].sum().sort_values(
    ascending=False
)

print(death_runs.head())
print(death_batters.head())

batting_team
Mumbai Indians                 9598
Chennai Super Kings            9061
Royal Challengers Bangalore    8417
Kolkata Knight Riders          8053
Rajasthan Royals               7281
Name: total_runs, dtype: int64
batter
MS Dhoni          2786
KA Pollard        1708
KD Karthik        1565
AB de Villiers    1421
RA Jadeja         1420
Name: batsman_runs, dtype: int64

Run Distribution Per Inning

In [39]:
inning_runs = deliveries_df.groupby(
    "inning"
)["total_runs"].mean()

print(inning_runs)

inning
1    1.342591
2    1.321733
3    1.779221
4    1.708333
5    1.375000
6    3.750000
Name: total_runs, dtype: float64

In [40]:
merged_df = deliveries_df.merge(
    matches_df,
    left_on="match_id",
    right_on="id"
)

Season-wise Trend Example

In [41]:
season_runs = merged_df.groupby(
    "season"
)["total_runs"].sum()

print(season_runs)

season
2007/08    17937
2009       16353
2009/10    18883
2011       21154
2012       22453
2013       22602
2014       18931
2015       18353
2016       18862
2017       18786
2018       19901
2019       19434
2020/21    19416
2021       18637
2022       24395
2023       25688
2024       25971
Name: total_runs, dtype: int64

Toss Impact Analysis

In [42]:
team_runs = deliveries_df.groupby(
    ["match_id", "batting_team"]
)["total_runs"].sum().reset_index()

toss_analysis = team_runs.merge(
    matches_df[["id", "toss_winner"]],
    left_on="match_id",
    right_on="id"
)

toss_analysis["is_toss_winner"] = (
    toss_analysis["batting_team"] == toss_analysis["toss_winner"]
)

result = toss_analysis.groupby(
    "is_toss_winner"
)["total_runs"].mean()

print(result)

is_toss_winner
False    161.351920
True     156.666972
Name: total_runs, dtype: float64

In [43]:
toss_win_advantage = (
    matches_df["toss_winner"] == matches_df["winner"]
).mean() * 100

print("Toss winner also won match:", toss_win_advantage, "%")

Toss winner also won match: 50.593607305936075 %

Player of Match Contribution

In [44]:
player_runs = deliveries_df.groupby(
    ["match_id", "batter"]
)["batsman_runs"].sum().reset_index()

highest_scorers = player_runs.loc[
    player_runs.groupby("match_id")["batsman_runs"].idxmax()
]

pom_analysis = highest_scorers.merge(
    matches_df[["id", "player_of_match"]],
    left_on="match_id",
    right_on="id"
)

pom_analysis["was_top_scorer"] = (
    pom_analysis["batter"] == pom_analysis["player_of_match"]
)

print(
    pom_analysis["was_top_scorer"].value_counts()
)

was_top_scorer
False    599
True     496
Name: count, dtype: int64

Venue-wise Analysis

In [45]:
matches_per_venue = matches_df.groupby(
    "venue"
)["id"].count().sort_values(
    ascending=False
)

print(matches_per_venue)

venue
Eden Gardens                                                             77
Wankhede Stadium                                                         73
M Chinnaswamy Stadium                                                    65
Feroz Shah Kotla                                                         60
Rajiv Gandhi International Stadium, Uppal                                49
MA Chidambaram Stadium, Chepauk                                          48
Sawai Mansingh Stadium                                                   47
Dubai International Cricket Stadium                                      46
Wankhede Stadium, Mumbai                                                 45
Punjab Cricket Association Stadium, Mohali                               35
Sheikh Zayed Stadium                                                     29
MA Chidambaram Stadium, Chepauk, Chennai                                 28
Sharjah Cricket Stadium                                                  28
Narendra Modi Stadium, Ahmedabad                                         24
Maharashtra Cricket Association Stadium                                  22
Dr DY Patil Sports Academy, Mumbai                                       20
Dr DY Patil Sports Academy                                               17
Brabourne Stadium, Mumbai                                                17
Subrata Roy Sahara Stadium                                               16
Arun Jaitley Stadium, Delhi                                              16
Eden Gardens, Kolkata                                                    16
Rajiv Gandhi International Stadium                                       15
M.Chinnaswamy Stadium                                                    15
Kingsmead                                                                15
Arun Jaitley Stadium                                                     14
M Chinnaswamy Stadium, Bengaluru                                         14
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    14
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     13
Maharashtra Cricket Association Stadium, Pune                            13
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      13
Sardar Patel Stadium, Motera                                             12
SuperSport Park                                                          12
Punjab Cricket Association IS Bindra Stadium, Mohali                     11
Saurashtra Cricket Association Stadium                                   10
Punjab Cricket Association IS Bindra Stadium                             10
Sawai Mansingh Stadium, Jaipur                                           10
Brabourne Stadium                                                        10
Holkar Cricket Stadium                                                    9
Himachal Pradesh Cricket Association Stadium                              9
MA Chidambaram Stadium                                                    9
Zayed Cricket Stadium, Abu Dhabi                                          8
New Wanderers Stadium                                                     8
Newlands                                                                  7
St George's Park                                                          7
Barabati Stadium                                                          7
JSCA International Stadium Complex                                        7
Shaheed Veer Narayan Singh International Stadium                          6
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          5
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        5
Nehru Stadium                                                             5
Green Park                                                                4
Himachal Pradesh Cricket Association Stadium, Dharamsala                  4
Buffalo Park                                                              3
De Beers Diamond Oval                                                     3
Vidarbha Cricket Association Stadium, Jamtha                              3
Barsapara Cricket Stadium, Guwahati                                       3
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam        2
OUTsurance Oval                                                           2
Name: id, dtype: int64

In [46]:
venue_runs = merged_df.groupby(
    ["venue", "match_id"]
)["total_runs"].sum().reset_index()

avg_venue_runs = venue_runs.groupby(
    "venue"
)["total_runs"].mean().sort_values(
    ascending=False
)

print(avg_venue_runs)

venue
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam       400.000000
Arun Jaitley Stadium, Delhi                                              380.687500
Eden Gardens, Kolkata                                                    380.312500
M Chinnaswamy Stadium, Bengaluru                                         380.142857
Himachal Pradesh Cricket Association Stadium, Dharamsala                 378.750000
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh         371.200000
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     364.846154
Brabourne Stadium                                                        348.100000
Punjab Cricket Association IS Bindra Stadium                             347.600000
Wankhede Stadium, Mumbai                                                 346.377778
Brabourne Stadium, Mumbai                                                342.588235
Sawai Mansingh Stadium, Jaipur                                           342.100000
M.Chinnaswamy Stadium                                                    341.800000
Barsapara Cricket Stadium, Guwahati                                      339.666667
Narendra Modi Stadium, Ahmedabad                                         339.583333
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur       335.000000
Saurashtra Cricket Association Stadium                                   333.300000
Dr DY Patil Sports Academy, Mumbai                                       328.650000
Barabati Stadium                                                         325.428571
Arun Jaitley Stadium                                                     324.500000
Green Park                                                               324.500000
Punjab Cricket Association IS Bindra Stadium, Mohali                     322.272727
Himachal Pradesh Cricket Association Stadium                             321.888889
Wankhede Stadium                                                         320.643836
Holkar Cricket Stadium                                                   319.111111
Maharashtra Cricket Association Stadium                                  318.500000
MA Chidambaram Stadium, Chepauk                                          318.270833
MA Chidambaram Stadium, Chepauk, Chennai                                 316.642857
Maharashtra Cricket Association Stadium, Pune                            316.000000
Dubai International Cricket Stadium                                      314.130435
Sardar Patel Stadium, Motera                                             313.916667
Punjab Cricket Association Stadium, Mohali                               313.914286
M Chinnaswamy Stadium                                                    311.738462
Zayed Cricket Stadium, Abu Dhabi                                         309.375000
Rajiv Gandhi International Stadium                                       308.733333
Eden Gardens                                                             307.246753
Feroz Shah Kotla                                                         307.016667
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    306.714286
Sharjah Cricket Stadium                                                  306.535714
Sheikh Zayed Stadium                                                     305.413793
SuperSport Park                                                          304.416667
Rajiv Gandhi International Stadium, Uppal                                303.836735
Sawai Mansingh Stadium                                                   303.489362
De Beers Diamond Oval                                                    299.000000
Vidarbha Cricket Association Stadium, Jamtha                             294.000000
JSCA International Stadium Complex                                       293.714286
St George's Park                                                         290.428571
Kingsmead                                                                290.200000
Shaheed Veer Narayan Singh International Stadium                         290.166667
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      288.153846
New Wanderers Stadium                                                    286.500000
MA Chidambaram Stadium                                                   284.777778
Subrata Roy Sahara Stadium                                               283.000000
Dr DY Patil Sports Academy                                               282.941176
Nehru Stadium                                                            272.600000
Buffalo Park                                                             266.333333
OUTsurance Oval                                                          264.500000
Newlands                                                                 256.714286
Name: total_runs, dtype: float64

City-wise Scoring Trends

In [47]:
city_runs = merged_df.groupby(
    ["city", "match_id"]
)["total_runs"].sum().reset_index()

avg_city_runs = city_runs.groupby(
    "city"
)["total_runs"].mean().sort_values(
    ascending=False
)

print(avg_city_runs)

city
Bengaluru         360.310345
Guwahati          339.666667
Dharamsala        339.384615
Mohali            335.000000
Rajkot            333.300000
Ahmedabad         331.027778
Mumbai            328.421965
Chandigarh        325.639344
Cuttack           325.428571
Kanpur            324.500000
Delhi             322.833333
Kolkata           319.817204
Indore            319.111111
Navi Mumbai       318.333333
Hyderabad         315.090909
Chennai           314.188235
Bangalore         311.738462
Jaipur            310.263158
Dubai             306.846154
Pune              306.725490
Lucknow           306.714286
Abu Dhabi         306.270270
Centurion         304.416667
Visakhapatnam     303.066667
Kimberley         299.000000
Nagpur            294.000000
Ranchi            293.714286
Port Elizabeth    290.428571
Durban            290.200000
Raipur            290.166667
Johannesburg      286.500000
Kochi             272.600000
East London       266.333333
Sharjah           265.900000
Bloemfontein      264.500000
Cape Town         256.714286
Name: total_runs, dtype: float64

In [48]:
print("Top 5 High Scoring Cities:")
print(avg_city_runs.head(5))

Top 5 High Scoring Cities:
city
Bengaluru     360.310345
Guwahati      339.666667
Dharamsala    339.384615
Mohali        335.000000
Rajkot        333.300000
Name: total_runs, dtype: float64

Season-wise Run Trends

In [49]:
season_runs = merged_df.groupby(
    "season"
)["total_runs"].sum()

print(season_runs)

season
2007/08    17937
2009       16353
2009/10    18883
2011       21154
2012       22453
2013       22602
2014       18931
2015       18353
2016       18862
2017       18786
2018       19901
2019       19434
2020/21    19416
2021       18637
2022       24395
2023       25688
2024       25971
Name: total_runs, dtype: int64

In [50]:
season_growth = season_runs.pct_change() * 100

print(season_growth)

season
2007/08          NaN
2009       -8.830908
2009/10    15.471167
2011       12.026691
2012        6.140683
2013        0.663608
2014      -16.241925
2015       -3.053193
2016        2.773389
2017       -0.402927
2018        5.935271
2019       -2.346616
2020/21    -0.092621
2021       -4.012155
2022       30.895530
2023        5.300266
2024        1.101682
Name: total_runs, dtype: float64

Winning Team Analysis

In [51]:
innings_runs = deliveries_df.groupby(
    ["match_id", "inning", "batting_team"]
)["total_runs"].sum().reset_index()

In [52]:
predicted_winners = []

for match in innings_runs["match_id"].unique():
    match_data = innings_runs[
        innings_runs["match_id"] == match
    ]
    
    if len(match_data) == 2:
        team1 = match_data.iloc[0]
        team2 = match_data.iloc[1]
        
        winner = (
            team1["batting_team"]
            if team1["total_runs"] > team2["total_runs"]
            else team2["batting_team"]
        )
        
        predicted_winners.append({
            "match_id": match,
            "predicted_winner": winner
        })

In [53]:
predicted_df = pd.DataFrame(predicted_winners)

In [54]:
final_winner_analysis = predicted_df.merge(
    matches_df[["id", "winner"]],
    left_on="match_id",
    right_on="id"
)

final_winner_analysis["correct_prediction"] = (
    final_winner_analysis["predicted_winner"] ==
    final_winner_analysis["winner"]
)

accuracy = (
    final_winner_analysis["correct_prediction"]
    .mean() * 100
)

print("Winner prediction accuracy:", accuracy, "%")

Winner prediction accuracy: 98.60853432282003 %

### ***Stage 5:*** 
- Derived Insights

In [55]:
# Most Consistent Batter

most_consistent_batter = consistent_batters.head(1)

print("Most Consistent Batter:")
print(most_consistent_batter)

Most Consistent Batter:
           batsman_runs  match_id
batter
DP Conway          42.0        22

In [56]:
# Best Death Over Team

best_death_team = death_runs.head(1)

print("Best Death Over Team:")
print(best_death_team)

Best Death Over Team:
batting_team
Mumbai Indians    9598
Name: total_runs, dtype: int64

In [57]:
# High Scoring Venues

high_scoring_venues = avg_venue_runs.head(5)

print("Top High Scoring Venues:")
print(high_scoring_venues)

Top High Scoring Venues:
venue
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam    400.000000
Arun Jaitley Stadium, Delhi                                           380.687500
Eden Gardens, Kolkata                                                 380.312500
M Chinnaswamy Stadium, Bengaluru                                      380.142857
Himachal Pradesh Cricket Association Stadium, Dharamsala              378.750000
Name: total_runs, dtype: float64

In [58]:
# Toss Advantage Insight

print("Toss Advantage Percentage:")
print(toss_win_advantage)
if toss_win_advantage > 50:
    print("Winning toss provides a slight advantage.")
else:
    print("Toss has minimal impact on match outcomes.")

Toss Advantage Percentage:
50.593607305936075
Winning toss provides a slight advantage.

In [59]:
# Highest Scoring City

top_city = avg_city_runs.head(1)

print("Highest Scoring City:")
print(top_city)

Highest Scoring City:
city
Bengaluru    360.310345
Name: total_runs, dtype: float64

### ***Stage 6:*** 
- Reporting

In [60]:
# Top Batters Report

top_batters_report = (
    deliveries_df.groupby("batter")["batsman_runs"]
    .sum()
    .reset_index()
    .sort_values(by="batsman_runs", ascending=False)
    .head(10)
)

top_batters_report.columns = [
    "Batter Name",
    "Total Runs"
]

print(top_batters_report)

        Batter Name  Total Runs
631         V Kohli        8014
512        S Dhawan        6769
477       RG Sharma        6630
147       DA Warner        6567
546        SK Raina        5536
374        MS Dhoni        5243
30   AB de Villiers        5181
124        CH Gayle        4997
501      RV Uthappa        4954
282      KD Karthik        4843

In [61]:
# Top Bowlers Economy Report

bowler_report = bowler_stats.reset_index().sort_values(
    by="economy",
    ascending=True
).head(10)

bowler_report = bowler_report[
    ["bowler", "total_runs", "overs", "economy"]
]

bowler_report.columns = [
    "Bowler Name",
    "Runs Conceded",
    "Overs Bowled",
    "Economy Rate"
]

print(bowler_report)

       Bowler Name  Runs Conceded  Overs Bowled  Economy Rate
24    AC Gilchrist              0      0.166667      0.000000
364     R Ravindra              7      2.000000      3.500000
317       NB Singh             18      4.166667      4.320000
460    Sachin Baby              8      1.666667      4.800000
38       AM Rahane              5      1.000000      5.000000
245  LA Carseldine              6      1.166667      5.142857
453      SS Mundhe              6      1.166667      5.142857
125    DJ Thornely             40      7.333333      5.454545
260       M Manhas             42      7.000000      6.000000
296       MW Short             25      4.166667      6.000000

In [62]:
# Venue Report

venue_report = avg_venue_runs.reset_index()

venue_report.columns = [
    "Venue",
    "Average Runs"
]

print(venue_report.head(10))

                                               Venue  Average Runs
0  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...    400.000000
1                        Arun Jaitley Stadium, Delhi    380.687500
2                              Eden Gardens, Kolkata    380.312500
3                   M Chinnaswamy Stadium, Bengaluru    380.142857
4  Himachal Pradesh Cricket Association Stadium, ...    378.750000
5  Punjab Cricket Association IS Bindra Stadium, ...    371.200000
6  Rajiv Gandhi International Stadium, Uppal, Hyd...    364.846154
7                                  Brabourne Stadium    348.100000
8       Punjab Cricket Association IS Bindra Stadium    347.600000
9                           Wankhede Stadium, Mumbai    346.377778

In [63]:
# City Report

city_report = avg_city_runs.reset_index()

city_report.columns = [
    "City",
    "Average Runs"
]

print(city_report.head(10))

         City  Average Runs
0   Bengaluru    360.310345
1    Guwahati    339.666667
2  Dharamsala    339.384615
3      Mohali    335.000000
4      Rajkot    333.300000
5   Ahmedabad    331.027778
6      Mumbai    328.421965
7  Chandigarh    325.639344
8     Cuttack    325.428571
9      Kanpur    324.500000

In [64]:
# Most Consistent Batter Report

consistent_report = consistent_batters.reset_index()

consistent_report.columns = [
    "Batter",
    "Average Runs Per Match",
    "Matches Played"
]

consistent_report = consistent_report.sort_values(
    by="Average Runs Per Match",
    ascending=False
)

print(consistent_report.head(10))

            Batter  Average Runs Per Match  Matches Played
0        DP Conway               42.000000              22
1  B Sai Sudharsan               41.360000              25
2         KL Rahul               38.434426             122
3      LMP Simmons               37.206897              29
4       RD Gaikwad               36.615385              65
5         SE Marsh               36.072464              69
6        DA Warner               35.690217             184
7         CH Gayle               35.439716             141
8        ML Hayden               34.593750              32
9       MEK Hussey               34.086207              58

### ***Stage 7:*** 
- Data Export

In [65]:
import os

# Create output directory
os.makedirs("output", exist_ok=True)

In [66]:
# Export Runs Per Match
runs_per_match = deliveries_df.groupby("match_id")["total_runs"]\
.sum().reset_index()

runs_per_match.to_csv(
    "output/runs_per_match.csv",
    index=False
)

In [67]:
# Export Team Scores Per Match

team_scores = deliveries_df.groupby(
    ["match_id", "batting_team"]
)["total_runs"].sum().reset_index()

team_scores.to_csv(
    "output/team_scores.csv",
    index=False
)

In [68]:
# Export Top Batters

top_batters = deliveries_df.groupby(
    "batter"
)["batsman_runs"].sum().reset_index()

top_batters = top_batters.sort_values(
    by="batsman_runs",
    ascending=False
).head(10)

top_batters.to_csv(
    "output/top_batters.csv",
    index=False
)

In [69]:
# Export Strike Rate

economy = deliveries_df.groupby("bowler").agg({
    "total_runs":"sum",
    "ball":"count"
}).reset_index()

economy["overs"] = economy["ball"] / 6
economy["economy_rate"] = (
    economy["total_runs"] /
    economy["overs"]
)

economy.to_csv(
    "output/economy.csv",
    index=False
)